import { createGlobalTheme } from '@vanilla-extract/css';
// import { modularScale } from 'polished';

// const createScale = (ratio: number, base: number) => (steps: number) =>
//   `${modularScale(steps, base, ratio)}px`;

// const borderRadiusScale = createScale(1.5, 4);

export const vars = createGlobalTheme(':root', {
  space: {
    'zero': '0',
    '3xs': '0.125rem',
    'xxs': '0.5rem',
    'xs': '0.75rem',
    'small': '1rem',
    'medium': '1.5rem',
    'large': '2rem',
    'xl': '2.5rem',
    'xxl': '3rem',
    '3xl': '3.5rem',
    '4xl': '4rem',
    '5xl': '4.5rem',
    '6xl': '5rem',
    '7xl': '5.5rem',
    '8xl': '6rem',
    '9xl': '6.5rem',
  },
  letterSpacing: {
    'zero': '0',
    '3xs': '-0.03em',
    'xxs': '-0.02em',
    'xs': '-0.01em',
    'small': '0.05em',
    'medium': '0.1em',
    'large': '0.15rem',
    'xl': '0.2rem',
    'xxl': '0.25rem',
    '3xl': '0.3rem',
    '4xl': '0.35rem',
    '5xl': '0.4rem',
    '6xl': '0.45rem',
    '7xl': '0.5rem',
    '8xl': '0.55rem',
    '9xl': '0.6rem',
  },
  fontWeight: {
    'xxs': '100',
    'xs': '200',
    'small': '300',
    'medium': '400',
    'large': '500',
    'xl': '600',
    'xxl': '700',
  },
  borderRadius: {
    // '1x': borderRadiusScale(1),
    // '2x': borderRadiusScale(2),
    // '3x': borderRadiusScale(3),
    // '4x': borderRadiusScale(4),
    // '5x': borderRadiusScale(5),
    'none': '0px',
    'circle': '50%',
    'full': '99999px',
  },
  fontFamily: {
    body: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
    heading: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
    description: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
  },
  lineHeight: {
    'zero': '0',
    '3xs': '0.125rem',
    'xxs': '0.5rem',
    'xs': '0.75rem',
    'small': '1rem',
    'medium': '1.5rem',
    'large': '2rem',
    'xl': '2.5rem',
    'xxl': '3rem',
    '3xl': '3.5rem',
    '4xl': '4rem',
    '5xl': '4.5rem',
    '6xl': '5rem',
    '7xl': '5.5rem',
    '8xl': '6rem',
    '9xl': '6.5rem',
  },
  maxWidth: {
    'xsmall': '576px',
    'small': '768px',
    'medium': '992px',
    'large': '1080px',
    'xlarge': '1200px',
    'full': 'none',
  },
  aspectRatio: {
    '1:1': '100%',
    '4:3': '75%',
    '3:2': '66.66%',
    '16:9': '56.25%',
    '2:3': '150%',
    '2:1': '200%',
  },
  fontStyle: {
    'italic': 'italic',
    'normal': 'normal',
  },
  textDecoration: {
    'overline': 'overline',
    'line-through': 'line-through',
    'underline': 'underline',
    'none': 'none',
  },
  gridTemplateColumns: {
    '1x': 'repeat(1,1fr)',
    '2x': 'repeat(2,1fr)',
    '3x': 'repeat(3,1fr)',
    '4x': 'repeat(4,1fr)',
    '5x': 'repeat(5,1fr)',
    '6x': 'repeat(6,1fr)',
    '7x': 'repeat(7,1fr)',
    '8x': 'repeat(8,1fr)',
    '9x': 'repeat(9,1fr)',
    '10x': 'repeat(10,1fr)',
    '11x': 'repeat(11,1fr)',
    '12x': 'repeat(12,1fr)',
  },
});
